
#set firewall group network-group OpenDNS network '208.67.222.222/32'
#set firewall group network-group OpenDNS network '208.67.220.220/32'


set firewall group network-group PRG0100-SERVICES-INTERNAL description 'WEBPROXY'
set firewall group network-group PRG0100-SERVICES-INTERNAL network '100.66.66.20/32'
set firewall group network-group PRG0300-SERVICES-INTERNAL description 'WEBPROXY'
set firewall group network-group PRG0300-SERVICES-INTERNAL network '100.66.66.20/32'
set firewall group network-group PRG0300-SERVICES-INTERNAL network '100.66.127.20/32'
set firewall group network-group PROXY_TESTDEV network '100.83.10.21/32'
set firewall group network-group PROXY_TESTDEV network '100.83.10.31/32'
set firewall group network-group PROXY_TESTDEV network '100.83.10.66/32'
set firewall group network-group PROXY_TESTDEV network '100.83.10.1/32'
set firewall group network-group NAT_TESTDEV description 'NAT TEST,DEV'
set firewall group network-group NAT_TESTDEV network '100.78.0.0/16'
set firewall group network-group NAT_TESTDEV network '100.82.0.0/16'
set firewall group network-group NAT_TESTDEV network '100.83.0.0/16'
set firewall group network-group NAT_TESTDEV network '100.85.0.0/16'
set firewall name ETH2_IN default-action 'drop'
set firewall name ETH2_IN description 'Pristup na Internet/NAT adresy'
set firewall name ETH2_IN rule 10 action 'accept'
set firewall name ETH2_IN rule 10 state established 'enable'
set firewall name ETH2_IN rule 10 state related 'enable'
set firewall name ETH2_IN rule 100 action 'accept'
set firewall name ETH2_IN rule 100 description 'Internet pro PRG0100-SERVICES-INTERNAL'
set firewall name ETH2_IN rule 100 source address '100.80.10.0/24'
set firewall name ETH2_IN rule 110 action 'accept'
set firewall name ETH2_IN rule 110 description 'Internet pro PRG0300-SERVICES-INTERNAL'
set firewall name ETH2_IN rule 110 source address '100.86.10.0/24'
set firewall name ETH2_IN rule 120 action 'accept'
set firewall name ETH2_IN rule 120 description 'Internet pro PRG0100-SERVICES-INTERNAL'
set firewall name ETH2_IN rule 120 destination port '80,443,53'
set firewall name ETH2_IN rule 120 protocol 'tcp_udp'
set firewall name ETH2_IN rule 120 source group network-group 'PRG0100-SERVICES-INTERNAL'
set firewall name ETH2_IN rule 130 action 'accept'
set firewall name ETH2_IN rule 130 description 'Internet pro PRG0300-SERVICES-INTERNAL'
set firewall name ETH2_IN rule 130 destination port '80,443,53'
set firewall name ETH2_IN rule 130 protocol 'tcp_udp'
set firewall name ETH2_IN rule 130 source group network-group 'PRG0300-SERVICES-INTERNAL'
set firewall name ETH2_IN rule 9900 action 'accept'
set firewall name ETH2_IN rule 9900 description 'Internet pro FBSD (DNS,NTP,SMTP,Web Proxy)'
set firewall name ETH2_IN rule 9900 source address '192.168.0.11-192.168.0.12'
set firewall name ETH2_IN rule 9910 action 'accept'
set firewall name ETH2_IN rule 9910 description 'Internet pro PRTG-W2K8 (MONITORING)'
set firewall name ETH2_IN rule 9910 source address '192.168.0.13-192.168.0.14'
set firewall name ETH2_IN rule 9920 action 'accept'
set firewall name ETH2_IN rule 9920 description 'Stroje co musi na internet (Legacy)'
set firewall name ETH2_IN rule 9920 source address '192.168.106.0/24'
set firewall name ETH2_IN rule 9931 action 'accept'
set firewall name ETH2_IN rule 9931 description 'DMZ co musi na Internet (SMTP)'
set firewall name ETH2_IN rule 9931 destination port '25,993'
set firewall name ETH2_IN rule 9931 protocol 'tcp'
set firewall name ETH2_IN rule 9931 source address '192.168.104.0/24'
set firewall name ETH2_IN rule 9932 action 'accept'
set firewall name ETH2_IN rule 9932 description 'DMZ DNS (SMTP)'
set firewall name ETH2_IN rule 9932 destination port '53'
set firewall name ETH2_IN rule 9932 protocol 'tcp_udp'
set firewall name ETH2_IN rule 9932 source address '192.168.104.0/24'
set firewall name ETH2_IN rule 9936 action 'accept'
set firewall name ETH2_IN rule 9936 description 'PRG0100 Monitoring'
set firewall name ETH2_IN rule 9936 protocol 'icmp'
set firewall name ETH2_IN rule 9936 source address '100.80.11.0/25'
set firewall name ETH2_IN rule 9937 action 'accept'
set firewall name ETH2_IN rule 9937 description 'PRG0300 Monitoring'
set firewall name ETH2_IN rule 9937 protocol 'icmp'
set firewall name ETH2_IN rule 9937 source address '100.86.11.0/25'
set firewall name ETH2_IN rule 9938 action 'accept'
set firewall name ETH2_IN rule 9938 description 'PRG0100 Monitoring'
set firewall name ETH2_IN rule 9938 destination port '21,43,80,443,10080'
set firewall name ETH2_IN rule 9938 protocol 'tcp'
set firewall name ETH2_IN rule 9938 source address '100.80.11.0/25'
set firewall name ETH2_IN rule 9939 action 'accept'
set firewall name ETH2_IN rule 9939 description 'PRG0300 Monitoring'
set firewall name ETH2_IN rule 9939 destination port '21,43,80,443,10080'
set firewall name ETH2_IN rule 9939 protocol 'tcp'
set firewall name ETH2_IN rule 9939 source address '100.86.11.0/25'
set firewall name ETH2_IN rule 9940 action 'accept'
set firewall name ETH2_IN rule 9940 description 'PRG0100 DNS Monitoring'
set firewall name ETH2_IN rule 9940 destination port '53'
set firewall name ETH2_IN rule 9940 protocol 'tcp_udp'
set firewall name ETH2_IN rule 9940 source address '100.80.11.0/25'
set firewall name ETH2_IN rule 9941 action 'accept'
set firewall name ETH2_IN rule 9941 description 'PRG0300 DNS Monitoring'
set firewall name ETH2_IN rule 9941 destination port '53'
set firewall name ETH2_IN rule 9941 protocol 'tcp_udp'
set firewall name ETH2_IN rule 9941 source address '100.86.11.0/25'
set firewall name ETH2_IN rule 9942 action 'accept'
set firewall name ETH2_IN rule 9942 description 'PRG03T1 DNS'
set firewall name ETH2_IN rule 9942 destination port '53'
set firewall name ETH2_IN rule 9942 protocol 'tcp_udp'
set firewall name ETH2_IN rule 9942 source group network-group 'NAT_TESTDEV'
set firewall name ETH2_IN rule 9943 action 'accept'
set firewall name ETH2_IN rule 9943 description 'PRG03T1'
set firewall name ETH2_IN rule 9943 protocol 'ip'
set firewall name ETH2_IN rule 9943 source group network-group 'NAT_TESTDEV'
set firewall name ETH2_IN rule 9944 action 'accept'
set firewall name ETH2_IN rule 9944 description 'PRG03T1 ICMP'
set firewall name ETH2_IN rule 9944 icmp type-name 'any'
set firewall name ETH2_IN rule 9944 protocol 'icmp'
set firewall name ETH2_IN rule 9944 source group network-group 'NAT_TESTDEV'
set firewall name ETH2_IN rule 9945 action 'accept'
set firewall name ETH2_IN rule 9945 description 'PRG03T1'
set firewall name ETH2_IN rule 9945 protocol 'ip'
set firewall name ETH2_IN rule 9945 source group network-group 'PROXY_TESTDEV'
set firewall name ETH2_IN rule 9946 action 'accept'
set firewall name ETH2_IN rule 9946 description 'ANSIBLE to AZURE'
set firewall name ETH2_IN rule 9946 destination address '104.47.146.94'
set firewall name ETH2_IN rule 9946 destination port '22'
set firewall name ETH2_IN rule 9946 protocol 'tcp'
set firewall name ETH2_IN rule 9946 source address '100.80.13.150'
set firewall name ETH2_IN rule 9947 action 'accept'
set firewall name ETH2_IN rule 9947 description 'ANSIBLE to AZURE'
set firewall name ETH2_IN rule 9947 destination address '104.46.44.2'
set firewall name ETH2_IN rule 9947 destination port '22'
set firewall name ETH2_IN rule 9947 protocol 'tcp'
set firewall name ETH2_IN rule 9947 source address '100.80.13.150'
set firewall name OUTSIDE_LOCAL default-action 'drop'
set firewall name OUTSIDE_LOCAL rule 5 action 'drop'
set firewall name OUTSIDE_LOCAL rule 5 description 'Limit ICMP Ping'
set firewall name OUTSIDE_LOCAL rule 5 icmp type-name 'echo-request'
set firewall name OUTSIDE_LOCAL rule 5 protocol 'icmp'
set firewall name OUTSIDE_LOCAL rule 5 recent count '5'
set firewall name OUTSIDE_LOCAL rule 5 recent time '1'
set firewall name OUTSIDE_LOCAL rule 10 action 'accept'
set firewall name OUTSIDE_LOCAL rule 10 state established 'enable'
set firewall name OUTSIDE_LOCAL rule 10 state related 'enable'
set firewall name OUTSIDE_LOCAL rule 15 action 'accept'
set firewall name OUTSIDE_LOCAL rule 15 description 'ICMP Ping'
set firewall name OUTSIDE_LOCAL rule 15 icmp type-name 'echo-request'
set firewall name OUTSIDE_LOCAL rule 15 protocol 'icmp'
set firewall name OUTSIDE_LOCAL rule 20 action 'drop'
set firewall name OUTSIDE_LOCAL rule 20 description 'SSH Limiting'
set firewall name OUTSIDE_LOCAL rule 20 destination port '2244'
set firewall name OUTSIDE_LOCAL rule 20 protocol 'tcp'
set firewall name OUTSIDE_LOCAL rule 20 recent count '5'
set firewall name OUTSIDE_LOCAL rule 20 recent time '30'
set firewall name OUTSIDE_LOCAL rule 20 state new 'enable'

set firewall name OUTSIDE_IN default-action 'drop'
set firewall name OUTSIDE_IN description 'Pristup na verejne komponenty'
set firewall name OUTSIDE_IN rule 10 action 'accept'
set firewall name OUTSIDE_IN rule 10 state established 'enable'
set firewall name OUTSIDE_IN rule 10 state related 'enable'
set firewall name OUTSIDE_IN rule 15 action 'drop'
set firewall name OUTSIDE_IN rule 15 state invalid 'enable'
set firewall name OUTSIDE_IN rule 17 action 'drop'
set firewall name OUTSIDE_IN rule 17 description 'Drop packets from Bogons'
set firewall name OUTSIDE_IN rule 17 source group network-group 'BOGON-NETWORKS'
set firewall name OUTSIDE_IN rule 20 action 'accept'
set firewall name OUTSIDE_IN rule 20 description 'ICMP RFC Required'
set firewall name OUTSIDE_IN rule 20 icmp type-name 'destination-unreachable'
set firewall name OUTSIDE_IN rule 20 protocol 'icmp'
set firewall name OUTSIDE_IN rule 25 action 'accept'
set firewall name OUTSIDE_IN rule 25 description 'ICMP RFC Required'
set firewall name OUTSIDE_IN rule 25 icmp type-name 'source-quench'
set firewall name OUTSIDE_IN rule 25 protocol 'icmp'
set firewall name OUTSIDE_IN rule 30 action 'accept'
set firewall name OUTSIDE_IN rule 30 description 'ICMP RFC Required'
set firewall name OUTSIDE_IN rule 30 icmp type-name 'time-exceeded'
set firewall name OUTSIDE_IN rule 30 protocol 'icmp'
set firewall name OUTSIDE_IN rule 35 action 'accept'
set firewall name OUTSIDE_IN rule 35 description 'ICMP RFC Required'
set firewall name OUTSIDE_IN rule 35 icmp type-name 'parameter-problem'
set firewall name OUTSIDE_IN rule 35 protocol 'icmp'
set firewall name OUTSIDE_IN rule 40 action 'accept'
set firewall name OUTSIDE_IN rule 40 description 'ICMP Ping Requests'
set firewall name OUTSIDE_IN rule 40 icmp type-name 'echo-request'
set firewall name OUTSIDE_IN rule 40 limit burst '10'
set firewall name OUTSIDE_IN rule 40 limit rate '10/second'
set firewall name OUTSIDE_IN rule 40 protocol 'icmp'




set firewall name OUTSIDE_IN rule 100 action 'accept'
set firewall name OUTSIDE_IN rule 100 description 'helpdesk.cloud4com.com (HTTP)'
set firewall name OUTSIDE_IN rule 100 destination address '192.168.104.167'
set firewall name OUTSIDE_IN rule 100 destination port '80,443'
set firewall name OUTSIDE_IN rule 100 protocol 'tcp'
set firewall name OUTSIDE_IN rule 100 state new 'enable'
set firewall name OUTSIDE_IN rule 110 action 'accept'
set firewall name OUTSIDE_IN rule 110 description 'www.cloud4com.com (HTTP)'
set firewall name OUTSIDE_IN rule 110 destination address '192.168.104.173'
set firewall name OUTSIDE_IN rule 110 destination port '80,443'
set firewall name OUTSIDE_IN rule 110 protocol 'tcp'
set firewall name OUTSIDE_IN rule 110 state new 'enable'
set firewall name OUTSIDE_IN rule 112 action 'accept'
set firewall name OUTSIDE_IN rule 112 description 'www.cloud4com.com (SSH pro Cognito.CZ)'
set firewall name OUTSIDE_IN rule 112 destination address '192.168.104.173'
set firewall name OUTSIDE_IN rule 112 destination port '22'
set firewall name OUTSIDE_IN rule 112 protocol 'tcp'
set firewall name OUTSIDE_IN rule 112 source address '141.170.130.19'
set firewall name OUTSIDE_IN rule 112 state new 'enable'
set firewall name OUTSIDE_IN rule 114 action 'accept'
set firewall name OUTSIDE_IN rule 114 description 'www.cloud4com.com (SSH pro Cognito.CZ)'
set firewall name OUTSIDE_IN rule 114 destination address '192.168.104.173'
set firewall name OUTSIDE_IN rule 114 destination port '22'
set firewall name OUTSIDE_IN rule 114 protocol 'tcp'
set firewall name OUTSIDE_IN rule 114 source address '81.19.4.135'
set firewall name OUTSIDE_IN rule 114 state new 'enable'
set firewall name OUTSIDE_IN rule 120 action 'accept'
set firewall name OUTSIDE_IN rule 120 description 'tco.cloud4com.com (HTTP)'
set firewall name OUTSIDE_IN rule 120 destination address '192.168.104.177'
set firewall name OUTSIDE_IN rule 120 destination port '80,443'
set firewall name OUTSIDE_IN rule 120 protocol 'tcp'
set firewall name OUTSIDE_IN rule 120 state new 'enable'
set firewall name OUTSIDE_IN rule 122 action 'accept'
set firewall name OUTSIDE_IN rule 122 description 'tco.loud4com.com (SSH pro Tetanet)'
set firewall name OUTSIDE_IN rule 122 destination address '192.168.104.177'
set firewall name OUTSIDE_IN rule 122 destination port '22'
set firewall name OUTSIDE_IN rule 122 protocol 'tcp'
set firewall name OUTSIDE_IN rule 122 source address '109.202.72.0/24'
set firewall name OUTSIDE_IN rule 122 state new 'enable'
set firewall name OUTSIDE_IN rule 124 action 'accept'
set firewall name OUTSIDE_IN rule 124 description 'virtix.net (SSH pro Aqua Digital)'
set firewall name OUTSIDE_IN rule 124 destination address '192.168.104.177'
set firewall name OUTSIDE_IN rule 124 destination port '22'
set firewall name OUTSIDE_IN rule 124 protocol 'tcp'
set firewall name OUTSIDE_IN rule 124 source address '78.108.103.198/32'
set firewall name OUTSIDE_IN rule 124 state new 'enable'
set firewall name OUTSIDE_IN rule 130 action 'accept'
set firewall name OUTSIDE_IN rule 130 description 'ns1.cloud4com.com (DNS)'
set firewall name OUTSIDE_IN rule 130 destination address '100.80.9.11'
set firewall name OUTSIDE_IN rule 130 destination port '53'
set firewall name OUTSIDE_IN rule 130 protocol 'tcp_udp'
set firewall name OUTSIDE_IN rule 130 state new 'enable'
set firewall name OUTSIDE_IN rule 200 action 'accept'
set firewall name OUTSIDE_IN rule 200 description 'PIGPEN Virtix (HTTP)'
set firewall name OUTSIDE_IN rule 200 destination address '100.80.8.11'
set firewall name OUTSIDE_IN rule 200 destination port '80,443'
set firewall name OUTSIDE_IN rule 200 protocol 'tcp'
set firewall name OUTSIDE_IN rule 200 state new 'enable'
set firewall name OUTSIDE_IN rule 210 action 'accept'
set firewall name OUTSIDE_IN rule 210 description 'PIGPEN KVM Proxy (HTTP)'
set firewall name OUTSIDE_IN rule 210 destination address '100.80.81.136'
set firewall name OUTSIDE_IN rule 210 destination port '443'
set firewall name OUTSIDE_IN rule 210 protocol 'tcp'
set firewall name OUTSIDE_IN rule 210 state new 'enable'
set firewall name OUTSIDE_IN rule 220 action 'accept'
set firewall name OUTSIDE_IN rule 220 description 'PIGPEN SFTP Servers (SFTP)'
set firewall name OUTSIDE_IN rule 220 destination group network-group 'PIGPEN-SFTP-SERVERS'
set firewall name OUTSIDE_IN rule 220 destination port '55022'
set firewall name OUTSIDE_IN rule 220 protocol 'tcp'
set firewall name OUTSIDE_IN rule 220 state new 'enable'
set firewall name OUTSIDE_IN rule 230 action 'accept'
set firewall name OUTSIDE_IN rule 230 description 'PIGPEN KVM Proxy (HTTP)'
set firewall name OUTSIDE_IN rule 230 destination address '100.86.87.136'
set firewall name OUTSIDE_IN rule 230 destination port '443'
set firewall name OUTSIDE_IN rule 230 protocol 'tcp'
set firewall name OUTSIDE_IN rule 230 state new 'enable'
set firewall name OUTSIDE_IN rule 500 action 'accept'
set firewall name OUTSIDE_IN rule 500 description 'ProtectV Proxy (HTTP APIs)'
set firewall name OUTSIDE_IN rule 500 destination address '100.80.81.140'
set firewall name OUTSIDE_IN rule 500 destination port '80,443'
set firewall name OUTSIDE_IN rule 500 protocol 'tcp'
set firewall name OUTSIDE_IN rule 500 source group network-group 'ProtectV'
set firewall name OUTSIDE_IN rule 500 state new 'enable'



set firewall name OUTSIDE_LOCAL default-action 'drop'
set firewall name OUTSIDE_LOCAL rule 5 action 'drop'
set firewall name OUTSIDE_LOCAL rule 5 description 'Limit ICMP Ping'
set firewall name OUTSIDE_LOCAL rule 5 icmp type-name 'echo-request'
set firewall name OUTSIDE_LOCAL rule 5 protocol 'icmp'
set firewall name OUTSIDE_LOCAL rule 5 recent count '5'
set firewall name OUTSIDE_LOCAL rule 5 recent time '1'
set firewall name OUTSIDE_LOCAL rule 10 action 'accept'
set firewall name OUTSIDE_LOCAL rule 10 state established 'enable'
set firewall name OUTSIDE_LOCAL rule 10 state related 'enable'
set firewall name OUTSIDE_LOCAL rule 15 action 'accept'
set firewall name OUTSIDE_LOCAL rule 15 description 'ICMP Ping'
set firewall name OUTSIDE_LOCAL rule 15 icmp type-name 'echo-request'
set firewall name OUTSIDE_LOCAL rule 15 protocol 'icmp'
set firewall name OUTSIDE_LOCAL rule 20 action 'drop'
set firewall name OUTSIDE_LOCAL rule 20 description 'SSH Limiting'
set firewall name OUTSIDE_LOCAL rule 20 destination port '2244'
set firewall name OUTSIDE_LOCAL rule 20 protocol 'tcp'
set firewall name OUTSIDE_LOCAL rule 20 recent count '5'
set firewall name OUTSIDE_LOCAL rule 20 recent time '30'
set firewall name OUTSIDE_LOCAL rule 20 state new 'enable'




set interfaces ethernet eth2 traffic-policy out 'SHAPE-IN'
set protocols ospf passive-interface-exclude 'eth2'


